# Netlify Configuration - محمد الناغي 2026
# موقع الحملة الانتخابية بتصميم عصري

[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  # ⚠️ غيّر هذا الرابط برابط Backend الخاص بك
  NEXT_PUBLIC_API_URL = "https://your-backend-url.com/api"
  NEXT_PUBLIC_SITE_NAME = "محمد الناغي"
  NEXT_PUBLIC_SITE_DESCRIPTION = "موقع المرشح محمد الناغي - دائرة منية النصر والجمالية - الدقهلية"

# إعادة توجيه للصفحات الديناميكية
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/news/:id"
  to = "/news/[id]"
  status = 200

[[redirects]]
  from = "/events/:id"
  to = "/events/[id]"
  status = 200

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"

# Cache Control للأصول الثابتة
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
