# Netlify Configuration - محمد الناغي 2026
# موقع الحملة الانتخابية بتصميم عصري + Backend Functions

[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  # API الآن داخلي عبر Netlify Functions
  NEXT_PUBLIC_API_URL = "/.netlify/functions"
  NEXT_PUBLIC_SITE_NAME = "محمد الناغي"
  NEXT_PUBLIC_SITE_DESCRIPTION = "موقع المرشح محمد الناغي - دائرة منية النصر والجمالية - الدقهلية"

# API Routes redirect to Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# إعادة توجيه للصفحات الديناميكية
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/news/:id"
  to = "/news/[id]"
  status = 200

[[redirects]]
  from = "/events/:id"
  to = "/events/[id]"
  status = 200

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"

# Cache Control للأصول الثابتة
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
