# Netlify Configuration - Root Level
# This file tells Netlify to build from the frontend folder

[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# API Routes redirect to Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Frontend Routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
